package com.kafka.producer.config.constant;

public class QueryConstant {

	
	public static final String VTUDTRNREQ_INSERT="INSERT INTO VTUDTRNREQ(UDIRTRNREFNO,TXNAMOUNT,APITYPE,APISUBTXNTYPE,TXNID,ORGTXNID,INITIATIONMODE,PURPOSECODE,ADJFLAG,ADJREASONCODE,RESPCODE,CRTBY,CRTIP,STATUSCODE,APITXNTYPE,MSGID,ORGTRNDATE,CUSTREFNO,TICKETNO) "
			+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?)";
	
	public static final String GET_UDIR_TRN_REF_NO="SELECT UDIRTRNREFNO_SEQ.NEXTVAL FROM DUAL ";
}
